USE [master]
GO

/****** Object:  Database [clinica_medica]    Script Date: 20/06/2023 15:38:40 ******/
CREATE DATABASE [clinica_medica]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'clinica_medica', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.SQLEXPRESS\MSSQL\DATA\clinica_medica.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'clinica_medica_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.SQLEXPRESS\MSSQL\DATA\clinica_medica_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT, LEDGER = OFF
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [clinica_medica].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [clinica_medica] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [clinica_medica] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [clinica_medica] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [clinica_medica] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [clinica_medica] SET ARITHABORT OFF 
GO

ALTER DATABASE [clinica_medica] SET AUTO_CLOSE ON 
GO

ALTER DATABASE [clinica_medica] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [clinica_medica] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [clinica_medica] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [clinica_medica] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [clinica_medica] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [clinica_medica] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [clinica_medica] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [clinica_medica] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [clinica_medica] SET  ENABLE_BROKER 
GO

ALTER DATABASE [clinica_medica] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [clinica_medica] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [clinica_medica] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [clinica_medica] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [clinica_medica] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [clinica_medica] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [clinica_medica] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [clinica_medica] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [clinica_medica] SET  MULTI_USER 
GO

ALTER DATABASE [clinica_medica] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [clinica_medica] SET DB_CHAINING OFF 
GO

ALTER DATABASE [clinica_medica] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [clinica_medica] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [clinica_medica] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [clinica_medica] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [clinica_medica] SET QUERY_STORE = ON
GO

ALTER DATABASE [clinica_medica] SET QUERY_STORE (OPERATION_MODE = READ_WRITE, CLEANUP_POLICY = (STALE_QUERY_THRESHOLD_DAYS = 30), DATA_FLUSH_INTERVAL_SECONDS = 900, INTERVAL_LENGTH_MINUTES = 60, MAX_STORAGE_SIZE_MB = 1000, QUERY_CAPTURE_MODE = AUTO, SIZE_BASED_CLEANUP_MODE = AUTO, MAX_PLANS_PER_QUERY = 200, WAIT_STATS_CAPTURE_MODE = ON)
GO

ALTER DATABASE [clinica_medica] SET  READ_WRITE 
GO

